parameters:

    # general info
    cocorico.site_name: %cocorico.site_name%
    cocorico.phone: %cocorico.phone%
    cocorico.address: %cocorico.address%
    cocorico.short_description: %cocorico.short_description%
    cocorico.contact_mail: %cocorico.contact_mail%
    cocorico.contact_mail_obfuscated: %cocorico.contact_mail_obfuscated%
    cocorico.from_email: %cocorico.from_email%
    cocorico.webmaster_email: %cocorico.webmaster_email%
    cocorico.vat_number: %cocorico.vat_number%

    # languages
    locale: %cocorico.knp_locale%
    cocorico.locale: %cocoricolocale%
    cocorico.locales: %cocorico.locales%
    cocorico.locales_string: %cocorico.locales_string%

    # currencies
    cocorico.currency: %cocorico.currency%
    cocorico.currencies_for_lexik: %cocorico.lexik_currencies%
    cocorico.currencies: %cocorico.currencies%
    cocorico.currencies_string: %cocorico.currencies_string%
    cocorico.currencies_json: %kernel.root_dir%/../web/json/currencies.json

    # VAT
    cocorico.include_vat: %cocorico.include_vat%
    cocorico.display_vat: %cocorico.display_vat%
    cocorico.vat: %cocorico.display_vat%

    # user
    cocorico.registration_confirmation: %cocorico.registration_confirmation%
    cocorico.fee_as_asker: %cocorico.fee_as_asker%
    cocorico.fee_as_offerer: %cocorico.fee_as_offerer%

    # time unit
    cocorico.time_unit: %cocorico.time_unit%
    cocorico.time_unit_flexibility: %cocorico.time_unit_flexibility%
    cocorico.time_unit_allday: %cocorico.time_unit_allday%
    cocorico.days_display_mode: %cocorico.days_display_mode%
    cocorico.times_display_mode: %cocorico.times_display_mode%

    # core
    cocorico.days_max: %cocorico.days_max%
    cocorico.days_max_edition: %cocorico.days_max_edition%
    cocorico.times_max: %cocorico.times_max%
    cocorico.time_picker: %cocorico.time_picker%
    cocorico.dashboard_max_per_page: %cocorico.dashboard_max_per_page%
    cocorico.message_max_per_page: %cocorico.message_max_per_page%
    cocorico.review_max_per_page: %cocorico.review_max_per_page%
    cocorico.listing_new_is_published: %cocorico.listing_new_is_published%
    cocorico.listing_countries: %cocorico.listing_countries%
    cocorico.listing_favorite_countries: %cocorico.listing_favorite_countries%
    cocorico.listing_category_min: %cocorico.listing_category_min%
    cocorico.listing_price_precision: %cocorico.listing_price_precision%
    cocorico.listing_price_min: %cocorico.listing_price_min%
    cocorico.listing_price_max: %cocorico.listing_price_max%
    cocorico.listing_map_display_marker: %cocorico.listing_map_display_marker%
    cocorico.listing_discount_min: %cocorico.listing_discount_min%
    cocorico.listing_discount_max: %cocorico.listing_discount_max%
    cocorico.listing_search_max_per_page: %cocorico.listing_search_max_per_page%
    cocorico.listing_search_min_result: %cocorico.listing_search_min_result%
    cocorico.listing.duplication: %cocorico.listing.duplication%
    cocorico.listing_availability_status: %cocorico.listing_availability_status%
    cocorico.booking_price_min: %cocorico.booking_price_min%
    cocorico.booking.allow_single_day: %cocorico.booking.allow_single_day%
    cocorico.booking.end_day_included: %cocorico.booking.end_day_included%
    cocorico.booking.min_start_delay: %cocorico.booking.min_start_delay%
    cocorico.booking.min_start_time_delay: %cocorico.booking.min_start_time_delay%
    cocorico.booking.cancelation_policy: %cocorico.booking.cancelation_policy%
    cocorico_listing_option.listing_option.entity_class: %cocorico_listing_option.listing_option.entity_class%
    cocorico_listing_option.booking_option.entity_class: %cocorico_listing_option.booking_option.entity_class%
    cocorico_listing_alert.entity_class: %cocorico_listing_alert.entity_class%
    cocorico_config.parameters_allowed: %cocorico_config.parameters_allowed%
    cocorico.user_img_min: %cocorico.user_img_min%
    cocorico.user_img_max: %cocorico.user_img_max%
    cocorico.user_img_max_upload_size: %cocorico.user_img_max_upload_size%
    cocorico.user_img_xsmall_w: %cocorico.user_img_xsmall_w%
    cocorico.user_img_xsmall_h: %cocorico.user_img_xsmall_h%
    cocorico.user_img_small_w: %cocorico.user_img_small_w%
    cocorico.user_img_small_h: %cocorico.user_img_small_h%
    cocorico.user_img_medium_w: %cocorico.user_img_medium_w%
    cocorico.user_img_medium_h: %cocorico.user_img_medium_h%
    cocorico.user_img_contact_w: %cocorico.user_img_contact_w%
    cocorico.user_img_contact_h: %cocorico.user_img_contact_h%
    cocorico.user_img_profile_w: %cocorico.user_img_profile_w%
    cocorico.user_img_profile_h: %cocorico.user_img_profile_h%
    cocorico.listing_img_min: %cocorico.listing_img_min%
    cocorico.listing_img_max: %cocorico.listing_img_max%
    cocorico.listing_img_max_upload_size: %cocorico.listing_img_max_upload_size%
    cocorico.listing_img_xsmall_w: %cocorico.listing_img_xsmall_w%
    cocorico.listing_img_xsmall_h: %cocorico.listing_img_xsmall_h%
    cocorico.listing_img_small_w: %cocorico.listing_img_small_w%
    cocorico.listing_img_small_h: %cocorico.listing_img_small_h%
    cocorico.listing_img_xxmedium_w: %cocorico.listing_img_xxmedium_w%
    cocorico.listing_img_xxmedium_h: %cocorico.listing_img_xxmedium_h%
    cocorico.listing_img_xmedium_w: %cocorico.listing_img_xmedium_w%
    cocorico.listing_img_xmedium_h: %cocorico.listing_img_xmedium_h%
    cocorico.listing_img_medium_w: %cocorico.listing_img_medium_w%
    cocorico.listing_img_medium_h: %cocorico.listing_img_medium_h%
    cocorico.listing_img_large_w: %cocorico.listing_img_large_w%
    cocorico.listing_img_large_h: %cocorico.listing_img_large_h%
    cocorico.listing_img_xlarge_w: %cocorico.listing_img_xlarge_w%
    cocorico.listing_img_xlarge_h: %cocorico.listing_img_xlarge_h%
    cocorico.listing_img_xxlarge_w: %cocorico.listing_img_xxlarge_w%
    cocorico.listing_img_xxlarge_h: %cocorico.listing_img_xxlarge_h%
    cocorico.upload_image_w: %cocorico.upload_image_w%
    cocorico.upload_image_h: %cocorico.upload_image_h%
    cocorico.listing_new_map_w: %cocorico.listing_new_map_w%
    cocorico.listing_new_map_h: %cocorico.listing_new_map_h%
    cocorico.listing_edit_map_w: %cocorico.listing_edit_map_w%
    cocorico.listing_edit_map_h: %cocorico.listing_edit_map_h%
    cocorico.listing_show_map_w: %cocorico.listing_show_map_w%
    cocorico.listing_show_map_h: %cocorico.listing_show_map_h%
    cocorico.listing_search_map_w: %cocorico.listing_search_map_w%
    cocorico.listing_search_map_h: %cocorico.listing_search_map_h%


    ################################### Environment dependant parameters. To override in parameters.yml ####
    #Assets base url for email
    cocorico.assets_base_urls: ~

    #Request Context url for email send from command
    router.request_context.host: ~
    router.request_context.scheme: ~
    router.request_context.base_url: ~

    #Admin access
    cocorico.admin: ~
    #Admin Web JMS translations activation
    cocorico.admin_translation: ~

    #translator key
    cocorico.translator.client.id: ~
    cocorico.translator.secret.key: ~
    cocorico.translator.translate.url: http://api.microsofttranslator.com/v2/Http.svc/TranslateArray
    cocorico.translator.scope.url: http://api.microsofttranslator.com
    cocorico.translator.token.url: https://datamarket.accesscontrol.windows.net/v2/OAuth2-13/
    cocorico.translator.grant.type: 'client_credentials'

    #facebook
    cocorico.facebook.app_id: ~
    cocorico.facebook.secret: ~

    #Image processing driver (liip_imagine_bundle): (gd, imagick, gmagick)
    cocorico.image_driver: ~

    #Google analytics code
    cocorico.google_analytics: ~

    #Google Tag Manager
    cocorico.google_tag_manager: ~

    #Google Place API Key (To set on prod)
    cocorico_geo.google_place_api_key: ~
    cocorico_geo.google_place_server_api_key: ~

    #IpInfoDb Api key
    cocorico_geo.ipinfodb_api_key: ~

    #Deployment
    cocorico.deploy.host: ~
    cocorico.deploy.dir: ~
    cocorico.deploy.user: ~

    #### Environment dependant only to facilitate tests ####

    #Booking expiration delay in minutes
    cocorico.booking.expiration_delay: ~ #2880

    #Expiring Bookings alert delay in minutes
    cocorico.booking.alert_expiration_delay: ~ #120

    #Imminent Bookings alert delay in minutes
    cocorico.booking.alert_imminent_delay: ~ #1440

    #Does the booking object (apartment, service, ...) is considered as validated (Offerer can be payed)
    #after booking start date or booking end date.
    cocorico.booking.validated_moment: ~ #'start'

    #Time after or before the moment the booking is considered as validated (in minutes)
    #If less than 0 the time is before the moment else time is after the moment
    cocorico.booking.validated_delay: ~ #0

    #Does the bank wire checking must be done really or simulated
    #Set to true in dev env to avoid to ask to mangopay to manually validate a bank wire
    #Set to false in prod env
    cocorico.bankwire_checking_simulation: ~ #false

    #### End Environment dependant ####


    ################################# Optional bundles #################################

    #SMS
    cocorico_sms.enabled: false
    cocorico_sms.ovh_endpoint_name:      "ovh-eu"
    cocorico_sms.ovh_application_key:    ~
    cocorico_sms.ovh_application_secret: ~
    cocorico_sms.ovh_consumer_key:       ~
    cocorico_sms.ovh_service_name:       ~
    cocorico_sms.ovh_debug:              false